# Generated by Django 5.2.5 on 2025-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("data_nascimento", models.DateField()),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("O", "Outro"),
                            ("N", "Prefiro não informar"),
                        ],
                        max_length=1,
                    ),
                ),
                ("endereco", models.TextField(blank=True)),
                ("cidade", models.CharField(blank=True, max_length=100)),
                ("estado", models.CharField(blank=True, max_length=2)),
                ("cep", models.CharField(blank=True, max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("suspenso", "Suspenso"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Candidato",
                "verbose_name_plural": "Candidatos",
                "ordering": ["nome"],
            },
        ),
    ]
