# Generated by Django 5.2.5 on 2025-10-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('esta_ativo', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('registro_funcional', models.CharField(blank=True, max_length=50)),
                ('vinculo', models.CharField(blank=True, max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'Prefiro não informar')], max_length=1)),
                ('endereco', models.TextField(blank=True)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConcursoCandidatosLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('esta_ativo', models.BooleanField(default=True)),
                ('concurso_uuid', models.UUIDField()),
                ('concurso_nome', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Lote de Candidatos do Concurso',
                'verbose_name_plural': 'Lotes de Candidatos dos Concursos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ConcursoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('esta_ativo', models.BooleanField(default=True)),
                ('codigo_inscricao', models.CharField(max_length=30)),
                ('pontos', models.CharField(blank=True, max_length=20)),
                ('opcao_concurso', models.CharField(blank=True, max_length=50)),
                ('codigo_cargo', models.CharField(blank=True, max_length=20)),
                ('cota', models.CharField(blank=True, max_length=50)),
                ('descricao_cargo', models.CharField(blank=True, max_length=200)),
                ('df', models.CharField(blank=True, max_length=50)),
                ('classificacao', models.IntegerField(blank=True)),
                ('classificacao_pcd', models.IntegerField(blank=True)),
                ('classificacao_nna', models.IntegerField(blank=True)),
                ('ano_concurso', models.CharField(blank=True, max_length=10)),
                ('observacao', models.TextField(blank=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concursos', to='candidatos.candidato')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='candidatos.concursocandidatoslote')),
            ],
            options={
                'verbose_name': 'Concurso do Candidato',
                'verbose_name_plural': 'Concursos dos Candidatos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
