# Generated by Django 5.2.5 on 2025-10-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concursocandidato',
            name='classificacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concursocandidato',
            name='classificacao_nna',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concursocandidato',
            name='classificacao_pcd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
