# Generated by Django 5.2.5 on 2025-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_concursocandidato_processo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursocandidato',
            name='ranking',
            field=models.IntegerField(default=0, verbose_name='Ranking'),
        ),
    ]
