# Generated by Django 5.2.5 on 2025-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0005_alter_concursocandidato_pontos'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursocandidato',
            name='categoria_efetiva',
            field=models.CharField(choices=[('GERAL', 'GERAL'), ('NNA', 'NNA'), ('PCD', 'PCD')], db_index=True, default='GERAL', max_length=10, verbose_name='Categoria Efetiva'),
        ),
        migrations.AddField(
            model_name='concursocandidato',
            name='promovido_de',
            field=models.CharField(blank=True, choices=[('NNA', 'NNA'), ('PCD', 'PCD')], max_length=10, null=True, verbose_name='Promovido de'),
        ),
        migrations.AddField(
            model_name='concursocandidato',
            name='promovido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Promovido em'),
        ),
        migrations.AddField(
            model_name='concursocandidato',
            name='promovido_para_geral',
            field=models.BooleanField(default=False, verbose_name='Promovido para Geral'),
        ),
        migrations.AlterField(
            model_name='concursocandidato',
            name='pontos',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Pontos'),
        ),
    ]
