# Generated by Django 5.2.5 on 2025-12-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0006_concursocandidato_categoria_efetiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursocandidato',
            name='ranking_escolha',
            field=models.IntegerField(default=0, verbose_name='Ranking da Escolha'),
        ),
    ]
