# Generated by Django 5.2.5 on 2026-01-20 19:11

import uuid
from django.db import migrations, models


def criar_parametrizacao_inicial(apps, schema_editor):
    """Cria um registro inicial de parametrização com valores padrão."""
    Parametrizacao = apps.get_model('candidatos', 'Parametrizacao')
    Parametrizacao.objects.create()


def reverter_parametrizacao_inicial(apps, schema_editor):
    """Remove o registro inicial de parametrização."""
    Parametrizacao = apps.get_model('candidatos', 'Parametrizacao')
    Parametrizacao.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("candidatos", "0007_concursocandidato_ranking_escolha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parametrizacao",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "esta_ativo",
                    models.BooleanField(default=True, verbose_name="Está Ativo?"),
                ),
                (
                    "porcentagem_pcd",
                    models.FloatField(
                        default=0.05,
                        help_text="Porcentagem padrão para cálculo de habilitados PCD (padrão: 0.05 = 5%)",
                        verbose_name="Porcentagem PCD",
                    ),
                ),
                (
                    "porcentagem_nna",
                    models.FloatField(
                        default=0.2,
                        help_text="Porcentagem padrão para cálculo de habilitados NNA (padrão: 0.20 = 20%)",
                        verbose_name="Porcentagem NNA",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parametrização",
                "verbose_name_plural": "Parametrizações",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.RunPython(
            criar_parametrizacao_inicial,
            reverter_parametrizacao_inicial
        ),
    ]
