# Generated by Django 5.2.5 on 2026-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidatos", "0018_remove_chave_inscrito"),
    ]

    operations = [
        migrations.AddField(
            model_name="concursocandidato",
            name="chave_inscrito",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Chave do Inscrito"
            ),
        ),
    ]
