# Generated by Django 5.2.5 on 2025-10-16 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidatos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidato",
            name="bairro",
            field=models.CharField(blank=True, max_length=120, verbose_name="Bairro"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="celular",
            field=models.CharField(blank=True, max_length=20, verbose_name="Celular"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="cep",
            field=models.CharField(blank=True, max_length=9, verbose_name="CEP"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="cpf",
            field=models.CharField(max_length=14, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="data_nascimento",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="endereco",
            field=models.TextField(blank=True, verbose_name="Endereço"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="estado",
            field=models.CharField(blank=True, max_length=2, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Masculino"),
                    ("F", "Feminino"),
                    ("O", "Outro"),
                    ("N", "Prefiro não informar"),
                ],
                max_length=1,
                verbose_name="Gênero",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="nome",
            field=models.CharField(max_length=200, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="numero",
            field=models.CharField(blank=True, max_length=20, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="registro_funcional",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Registro Funcional"
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="rg",
            field=models.CharField(blank=True, max_length=20, verbose_name="RG"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("inativo", "Inativo"),
                    ("suspenso", "Suspenso"),
                ],
                default="ativo",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="candidato",
            name="vinculo",
            field=models.CharField(blank=True, max_length=100, verbose_name="Vínculo"),
        ),
    ]
