# Generated by Django 5.2.5 on 2025-11-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_alter_candidato_bairro_alter_candidato_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursocandidato',
            name='processo_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID do Processo'),
        ),
    ]
