# Generated by Django 5.2.5 on 2025-12-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_concursocandidato_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concursocandidato',
            name='pontos',
            field=models.FloatField(blank=True, null=True, verbose_name='Pontos'),
        ),
    ]
