# Generated by Django 5.2.5 on 2026-02-10 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0009_remover_mascara_cpf_candidato'),
        ('candidatos', '0011_alter_concursocandidatoeliminacao_id_and_more'),
    ]

    operations = [
    ]
