# Generated by Django 5.2.5 on 2026-02-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0012_merge_20260210_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursocandidatoreclassificacao',
            name='processo_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Processo UUID'),
        ),
    ]
