# Generated by Django 5.2.5 on 2026-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0013_concursocandidatoreclassificacao_processo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursocandidatoeliminacao',
            name='processo_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID do Processo'),
        ),
    ]
