# Generated by Django 5.2.5 on 2026-03-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0014_concursocandidatoeliminacao_processo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursocandidatoreclassificacao',
            name='nova_classificacao',
            field=models.CharField(blank=True, choices=[('GERAL', 'GERAL'), ('NNA', 'NNA'), ('PCD', 'PCD')], default='GERAL', max_length=5, null=True, verbose_name='Nova Classificação'),
        ),
        migrations.AlterField(
            model_name='concursocandidatoreclassificacao',
            name='desclassificado_de',
            field=models.CharField(choices=[('GERAL', 'GERAL'), ('NNA', 'NNA'), ('PCD', 'PCD')], max_length=5, verbose_name='Desclassificado de'),
        ),
    ]
