# Generated by Django 5.2.5 on 2026-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidatos", "0016_remove_unique_cpf_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="concursocandidato",
            name="chave_inscrito",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Chave do Inscrito"
            ),
        ),
        migrations.AddField(
            model_name="concursocandidato",
            name="codigo_sigpec",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Código SIGPEC (Empresa)"
            ),
        ),
        migrations.AddField(
            model_name="concursocandidato",
            name="numero_lote",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número do Lote"
            ),
        ),
        migrations.AddField(
            model_name="concursocandidato",
            name="numero_vaga",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Número da Vaga"
            ),
        ),
    ]
