# Generated by Django 5.2.5 on 2026-07-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidatos", "0018_remove_parametrizacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="concursocandidatoreclassificacao",
            name="mandado_judicial",
            field=models.BooleanField(
                default=False, verbose_name="Mandado judicial"
            ),
        ),
    ]
