# Generated by Django 5.2.5 on 2026-07-31 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidatos",
            "0019_concursocandidatoreclassificacao_mandado_judicial",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="concursocandidatoreclassificacao",
            unique_together=set(),
        ),
    ]
