# Generated by Django 5.2.5 on 2026-08-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "candidatos",
            "0020_alter_concursocandidatoreclassificacao_unique_together",
        ),
        ("candidatos", "0022_move_mandado_judicial_to_concurso_candidato"),
    ]

    operations = []
